name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest

    steps:
      - id: "checkout"
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER_ID }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - id: "setup-node"
        name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "19.x"

      - name: "yarn install"
        run: yarn install

      - name: "yarn build"
        run: yarn build

      - id: "deploy"
        uses: "google-github-actions/deploy-appengine@v1"
        with:
          project_id: ${{ secrets.PORTFOLIO_PROJECT }}
          deliverables: app.yaml
